PORT_FORWARD_PLUGIN = "portforward_plugin"
PORT_FORWARD = "PORTFORWORD"

PORT_FORWARD_PLUGIN_TOPIC = "q-portforward-plugin"
PORT_FORWARD_AGENT = "PortForward Agent"
PORT_FORWARD_AGENT_TOPIC = "portforward-agent"

PORT_FORWARD_PLUGIN_NAME = "PORTFORWORD"
PORT_FORWARD_PATH_PREFIX = ""
